language: cpp

compiler:
  - g++

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo add-apt-repository ppa:boost-latest/ppa -y
    - sudo apt-get update
    - sudo apt-get --assume-yes install gcc-4.9 g++-4.9 libboost1.55-dev
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20;
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20;
    - sudo update-alternatives --config gcc;
    - sudo update-alternatives --config g++;

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make
  - ./sweettest

notifications:
  email: false
